services:
  vue-dev:
    container_name: biblioteca-vue
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5173:5173'
    volumes:
      - .:/app

    environment:
      - CHOKIDAR_USEPOLLING=true
